version: '3.0'

services:
  frontend:
    image: ticketfrei/frontend
    #    command: python3 frontend.py > /var/log/ticketfrei/frontend.log
    volumes:
      - ./config.toml:/srv/ticketfrei/config.toml
      - ./db.sqlite:/var/ticketfrei/db.sqlite
      - ./frontend.log:/var/log/ticketfrei/error.log
    labels:
      - traefik.enable=true
      - traefik.frontend.rule=Host:ticketfrei.example.org
      - traefik.port=80

  backend:
    image: ticketfrei/backend
    volumes:
      - ./config.toml:/srv/ticketfrei/config.toml
      - ./db.sqlite:/var/ticketfrei/db.sqlite
      - ./backend.log:/var/log/ticketfrei/backend.log

  proxy:
    image: traefik
    command: --configFile=/traefik.toml
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./traefik/traefik.toml:/traefik.toml
      - ./traefik/acme.json:/acme.json
      - /var/run/docker.sock:/var/run/docker.sock

