version: '3.0'

services:
  frontend:
    image: tf-frontend
    #    command: python3 frontend.py > /var/log/ticketfrei/frontend.log
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./config.toml:/srv/ticketfrei/config.toml
      - ./db.sqlite:/var/ticketfrei/db.sqlite
      - ./frontend.log:/var/log/ticketfrei/error.log

  backend:
    image: tf-backend
    volumes:
      - ./config.toml:/srv/ticketfrei/config.toml
      - ./db.sqlite:/var/ticketfrei/db.sqlite
      - ./backend.log:/var/log/ticketfrei/backend.log

